django_webcrawler/urls.py
from django.contrib import admin
from django.urls import path, include
from fapp import views

#Call functions in views.py

urlpatterns = [
    path('', views.LoginView.as_view(), name='index'),
    path("admin/", admin.site.urls),
    path("fapp/",include('fapp.urls')),  #domain_name/fapp/
    path("search/", include('search_app.urls')), #domain_name/search/

]

fapp/urls.py
from django.urls import path
from fapp import views

#Tamplate Tagging

app_name = 'fapp'

urlpatterns = [
    path('search/', views.search.as_view(), name='search') ,    #domain_name/fapp/search
    path('register/',views.register.as_view(),name='register'),
    path("user_login/", views.user_login.as_view(), name='user_login') , 
    path('user_logout/', views.user_logout.as_view, name='user_logout'),
    path('verifymail/', views.sendmail.as_view(), name="sendmail"),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email.as_view(), name='verify-email-confirm'),
    path('resetpwd/', views.resetpage.as_view(), name='reset'),

]

fapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# class User(models.Model):
#     first_name = models.CharField(max_length=128)
#     last_name = models.CharField(max_length=128)
#     email_field = models.EmailField(max_length=254, unique=True)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #default: on_delete=models.CASCADE
    # portfolio_site = models.URLField(blank=True) 
    # profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    def __str__(self):
        return self.user.username

fapp/forms.py
from typing import Any
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from fapp.models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email', 'password',)
    # name = forms.CharField(validators= [check_for_z])
    # email = forms.EmailField(max_length=100, label='Email')
    # verifyemail = forms.EmailField(max_length=100, label='Verify your email address')
    # text = forms.CharField(widget=forms.Textarea)
    # botcatcher = forms.CharField(required=False,
    #                              widget=forms.HiddenInput,
    #                              validators=[validators.MaxLengthValidator(0)])
    
    #validate the form, equivalent to validators

    # def clean_botcatcher(self) -> dict[str, Any]:
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("Gotcha Bot")
        
    #     return botcatcher
                                
    #Clean All data and dael with them

    #  def clean(self):
    #     all_clean_data = super().clean()
    #     email  = all_clean_data['email']
    #     vemail = all_clean_data['verifyemail']

    #     if email!= vemail:
    #         raise forms.ValidationError('Email and verify email do not match')

# class UserProfileForm(forms.ModelForm):
#     class Meta():
#         model = UserProfile
#         fields = ('portfolio_site', 'profile_pic')
        # fields = ('portfolio_site')


   

fapp/views.py
from django.shortcuts import render, redirect
from fapp.forms import UserForm  #, UserProfileForm
from django.views import View #CBV

#Login libraries

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib import messages

#Mail libraries

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .token import account_activation_token

# Create your views here.

class LoginView(View):
    def get(self, request):
        return render(request, 'fapp/index.html')

@method_decorator(login_required, name='dispatch') #Only active if logged in
class search(View):
    def get(self, request):
        return render(request, 'fapp/search.html')  

class user_logout(View):
    def log_out(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('fapp:index'))

#註冊
class register(View):
    def get(self, request):
        registered = False
        user_form = UserForm()
        # profile_form = UserProfileForm()
        return render(request, 'fapp/registration.html', 
                    {'user_form': user_form, 
                    'registered': registered})
    
    def post(self, request):

        registered = False
        user_form = UserForm(data=request.POST)
        # profile_form = UserProfileForm(data=request.POST)
        if user_form.is_valid():
        # if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # profile = profile_form.save(commit=False) # don't commit to the database
            # profile.user = user #set 1 to 1 relationship

            # if 'profile_pic' in  request.FILES:
            #     profile.profile_pic = request.FILES['profile_pic']

            # profile.save()

            registered = True

        else:
            # print(user_form.errors, profile_form.errors)
            print(user_form.errors)
            
        return render(request, 'fapp/registration.html', 
                    {'user_form': user_form, 
                    'registered': registered})

    # return render(request, 'fapp/registration.html', 
    #               {'user_form': user_form, 
    #                'profile_form': profile_form,
    #                'registered': registered})

#登入函數
class user_login(View):
    def get(self, request):
        return render(request, 'fapp/index.html', {})

    def post(self, request):

        email_address = request.POST.get('email') # get username that equals the input name='email' in login page
        password = request.POST.get('password') # get password that equals the input name='password' in login page
        user = authenticate(username=email_address, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('fapp:search'))
            else:
                return render(request, 'fapp/index.html', {'error_message': 'Inactive Account'})
            
        else:
            print(user)
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(email_address,password))
            return render(request, 'fapp/index.html', {'error_message': 'Invalid Email or Password'})


#發送郵件&重設密碼
@method_decorator(login_required, name='dispatch') 
class sendmail(View):

    def get(self, request):
        return render(request, 'fapp/resetpwd.html')
    
    def post(self, request):

        if request.user.is_authenticated:

            current_site = get_current_site(request)

            #電子郵件內容模板
            email_content = render_to_string(
                "fapp/email_template.html",
                {'username': request.user.username.split('.')[0],
                 'request': request,
                 'domain': current_site.domain,
                 'uid':urlsafe_base64_encode(force_bytes(request.user.pk)),
                 'token':account_activation_token.make_token(request.user),
                 })
        
            if request.method == 'POST':

                email = EmailMessage(
                    '【EY Web Crawler】重設密碼通知',  # 電子郵件標題
                    email_content,  # 電子郵件內容
                    settings.EMAIL_HOST_USER,  # 寄件者
                    [request.user.username]  # 收件者
                )
                email.fail_silently = False
                email.send()
                messages.error(request, "驗證信已寄出，請使用新密碼登入") 

                return render(request, 'fapp/index.html', {})
            
        else:
            return HttpResponseRedirect(reverse('fapp:search'))
            # return render(request, 'fapp/index.html', {'error_message': 'Invalid User'})

#電子郵件驗證連結
class verify_email(View):

    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('fapp:reset'))
        else:
            return HttpResponse('Activation link is invalid!')

#重設密碼連頁面 待後續調整
class resetpage(View):
    def get(self, request):
        return render(request, 'fapp/mail_reset.html')
    

templates/fapp/base.html
{% load static %}
<!DOCTYPE html>

<html> 
    <head>
        <meta charset='utf-8' >
        <title>首頁</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        {% comment %} <link rel="stylesheet" href="{% static "css/style.css" %}" /> {% endcomment %}
        <style>
            .container_signin {

                {% comment %} display: flex; {% endcomment %}
                {% comment %} align-items: stretch; {% endcomment %}
            
                padding-top: 30px;
                padding-bottom: 30px;
                padding-left: 60px;
                padding-right: 60px;
            
              }

              {% comment %} .col-md-4, .col-md-8 {

                flex: 1;
            } {% endcomment %}

        </style>
    </head>
    <body>
        
        <div class="container1">
            <nav class="navbar navbar-default navbar-inverse">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#">
                    <img src="https://yt3.googleusercontent.com/y50mwtpe8kFDoZACJPMB0SLFyN5-YD0lNj6qbsD6lgywAcgtNPydunjXj5wujqem-z3rrT8Ugw=s900-c-k-c0x00ffffff-no-rj" alt="EY.png is not found" class="img-circle" width="25" height="25">
                  </a>
                </div>
            
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li><a href="#">Sign In <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                      </ul>
                    </li>
                  </ul>
                  <form class="navbar-form navbar-left">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search Something">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                  </form>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Hello, Payne!</a></li>
                    {% block navbar %}
                    <li class="dropdown" id="resetpwd">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                    </li>
                    {% endblock %}
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
          </div>

          {% block body_block %}
          
          {% if messages %}
              <ul class="messages">
                  {% for msg in messages %}
                      alert('{{ msg.message }}')
                  {% endfor %}
              </ul>
          {% endif %}
          
          {% endblock  %}

    </body>
</html>

templates/fapp/email_template.html
<!-- Generate Email Content -->

{{ username }} 您好:

請點擊下方連結重設密碼:

{{ request.scheme }}://{{ domain }}{% url 'fapp:verify-email-confirm' uidb64=uid token=token %}

templates/fapp/index.html
{% load static %}
<!DOCTYPE html>
<!-- Login Page -->

<html> 
    <head>
        <meta charset='utf-8' >
        <title>首頁</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        {% comment %} <link rel="stylesheet" href="{% static "css/style.css" %}" /> {% endcomment %}
        <style>
            .container_signin {

                {% comment %} display: flex; {% endcomment %}
                {% comment %} align-items: stretch; {% endcomment %}
            
                padding-top: 30px;
                padding-bottom: 30px;
                padding-left: 60px;
                padding-right: 60px;
            
              }

              {% comment %} .col-md-4, .col-md-8 {

                flex: 1;
            } {% endcomment %}

        </style>
    </head>
    <body>
        
        <div class="container1">
            <nav class="navbar navbar-default navbar-inverse">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#">
                    <img src="https://yt3.googleusercontent.com/y50mwtpe8kFDoZACJPMB0SLFyN5-YD0lNj6qbsD6lgywAcgtNPydunjXj5wujqem-z3rrT8Ugw=s900-c-k-c0x00ffffff-no-rj" alt="EY.png is not found" class="img-circle" width="25" height="25">
                  </a>
                </div>
            
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li><a href="#">Sign In <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                      </ul>
                    </li>
                  </ul>
                  <form class="navbar-form navbar-left">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search Something">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                  </form>
                  <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Hello, Payne!</a></li>
                    {% block navbar %}
                    <li class="dropdown" id="resetpwd">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                      </ul>
                    </li>
                    {% endblock %}
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container-fluid -->
            </nav>
          </div>
    

          {% block body_block %}

          {% if messages %}
            <script>
                {% for msg in messages %}
                    alert('{{ msg.message }}');
                {% endfor %}
            </script>
          {% endif %}

          <div class="container_signin">
            <div class="row">
            
              <div class="col-md-4">
                <div class="img">
                  <img class="img-rounded" src="https://media.cakeresume.com/image/upload/s--P7J1QGjp--/c_pad,fl_png8,h_400,w_400/v1571100801/ralp6sizjsakkev5boho.png" alt="EY.png is not found" width="300" height="300">
                </div>
              </div>    
              
              
              <div class='col-md-8'>

                {% if error_message %}

                  <div class="alert alert-danger" role="alert">
                      <p>{{ error_message }}</p>
                  </div>

                {% endif %} 

                <form method='post' action="{% url 'fapp:user_login' %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="exampleInputEmail1">Email address</label>
                    <input type="text" class="form-control" name="email" placeholder="Email">      
                    <p class="help-block">   EX. Payne.Pe.Yeh@tw.ey.com</p>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" name="password" placeholder="Password">                   
                  </div>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox"> Remember me
                    </label>
                  </div>                  
                  <button type="submit" class="btn btn-primary" value="Submit">Log In</button>                 
                </form>                                   
              </div>              
            </div>
          </div>
    
          <div class="container">
            <div class="jumbotron">
              <h1>EY Tender Crawler</h1>
              <p>An web crawler application for internal employees</p>
              <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
            </div>
          </div>
                     
        {% endblock  %}

    </body>
</html>

templates/fapp/mail_reset.html
<!DOCTYPE html>
<!-- Page for resetting the passwore -->

{% extends "fapp/base.html" %}

{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Reset Your Password</h1>
        <form method="post" action="{% url 'fapp:reset' %}">
            {% csrf_token %}
            <p>Click the button and send a mail to reset your password. </p>
            <div class="form-group">
                <label for="exampleInputEmail1">Input Your Email address</label>
                <input type="text" class="form-control" name="email" placeholder="Email">      
                <p class="help-block">   EX. Payne.Pe.Yeh@tw.ey.com</p>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Input Your Old Password</label>
                <input type="password" class="form-control" name="password" placeholder="Old Password">                   
              </div>

              <div class="form-group">
                <label for="ResetInputPassword1">Input New Password</label>
                <input type="password" class="form-control" name="password" placeholder="New Password">                   
              </div>

              <div class="form-group">
                <label for="ResetInputPassword2">Input New Password Again</label>
                <input type="password" class="form-control" name="password" placeholder="New Password Again">                   
              </div>
            <p><button type="submit" class="btn btn-primary btn-lg" value='submit' >Reset Password</button></p>
        </form>
    </div>
</div>

{% endblock %}

templates/fapp/registration.html
<!DOCTYPE html>

{% extends "fapp/base.html" %}
{% load static %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>
  </div>

{% endblock %}

templates/fapp/resetpwd.html
<!DOCTYPE html>
{% extends "fapp/base.html" %}

{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Reset Password</h1>
        <form method="post" action="{% url 'fapp:sendmail' %}">
            {% csrf_token %}
            <p>Click the button and send a mail to reset your password. </p>
            <p><button type="submit" class="btn btn-primary btn-lg" value='submit' >Reset Password</button></p>
        </form>
    </div>
</div>

{% if messages %}
    <ul class="messages">
        {% for msg in messages %}
            alert('{{ msg.message }}')
        {% endfor %}
    </ul>
{% endif %}

{% endblock  %}

templates/fapp/result.html
<!DOCTYPE html>
<!-- Showing the search result -->
<!-- Haven't finished yet -->

{% extends "fapp/base.html" %}
{% load static %}

  {% block body_block %}

  <h1>Search Result!</h1>
  <div class="container">
    <div class="row">    
        <img src="{% static 'table.png' %}" alt="Example Image" width='600' height='200'>
    </div><!-- /.row -->
  </div>
  
  {% endblock  %}

templates/fapp/search.html
<!DOCTYPE html>
<!-- Search Page -->

{% extends "fapp/base.html" %}

{% block styles %}

{% endblock %}
  {% block body_block %}
  <style>
    /* 您的背景圖片樣式 */
    body {
        background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.6)), url('https://memeprod.ap-south-1.linodeobjects.com/user-template/a17e96b7884bba60c0a2cf9b27f8ee48.png');
        background-size: cover;
        background-position: center;
        height: 100vh;  
        animation: slide 10s linear infinite;
        
        /* 其他樣式 */
    }
    {% comment %} body:hover {
        background-position: left bottom;
      } {% endcomment %}

    @keyframes move {
        100% {
          transform: translateX(-66.6666%);
        }
    }

    .input-group {
        position: absolute;
        top: 50%;
        left: 20%;
        right: 20%;
    }

    .head {
        position: absolute;
        top: 35%;
        left: 35%;
        {% comment %} right: 20%; {% endcomment %}
        {% comment %} text-align: center; {% endcomment %}
        font-size: 50px;
        color: white;
    }

    /* 您的標題樣式 */
    h1 {
        font-size: 50px;
        color: white;
        text-align: center;
    }
</style>

 <div class="head">
    <h2><strong>Scrape Tenders You Desire</strong></h2>
 </div>
  

  <div class="searchbox">
    
    <form method='get' class="input-group">
        <input type="text" class="form-control" placeholder="Search Something....">
        <span class="input-group-btn">
            <button class="btn btn-primary" type="button">Search</button>
        </span>
    </form><!-- /input-group -->
       
  </div>

  {% comment %} <div class="container">
    <div class="row justify-content-center">    
        <div class="col-md-6">
            <form method='get' class="input-group">
                <input type="text" class="form-control" placeholder="Search KeyWord....">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="button">Search</button>
                </span>
            </form><!-- /input-group -->
        </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->
  </div> {% endcomment %}

  {% endblock  %}

<!-- 重設密碼按鈕 -->
  
{% block navbar %}
  <li class="nav-item" id="resetpwd"> 
      <a class="nav-link" href={% url 'fapp:sendmail' %}>Reset Password</a>
  </li>
{% endblock %}
  